### ISSUE TITLE
sqlalchemy: unable to open database

### ISSUE THREAD

**Issue by Florian95** [fhats/partify#132]
Hi,

I just install partify via easy_install. Version 0.4.1

But partify doesn't start. mopidy is started.

$ run_partify
Traceback (most recent call last):
  File "/usr/local/bin/run_partify", line 5, in <module>
    pkg_resources.run_script('Partify==0.4.1', 'run_partify')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1214, in run_script
  File "/usr/local/lib/python2.7/dist-packages/Partify-0.4.1-py2.7.egg/EGG-INFO/scripts/run_partify", line 23, in <module>
  File "build/bdist.linux-armv6l/egg/partify/**init**.py", line 86, in start
  File "build/bdist.linux-armv6l/egg/partify/database.py", line 35, in init_db
  File "/usr/local/lib/python2.7/dist-packages/Flask_SQLAlchemy-0.16-py2.7.egg/flask_sqlalchemy.py", line 822, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python2.7/dist-packages/Flask_SQLAlchemy-0.16-py2.7.egg/flask_sqlalchemy.py", line 814, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), tables=tables)
  File "build/bdist.linux-armv6l/egg/sqlalchemy/schema.py", line 2784, in create_all
  File "build/bdist.linux-armv6l/egg/sqlalchemy/engine/base.py", line 1486, in _run_visitor
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-armv6l/egg/sqlalchemy/engine/base.py", line 1479, in _optional_conn_ctx_manager
  File "build/bdist.linux-armv6l/egg/sqlalchemy/engine/base.py", line 1669, in contextual_connect
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 272, in connect
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 425, in __init__
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 855, in _do_get
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 225, in _create_connection
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 318, in __init__
  File "build/bdist.linux-armv6l/egg/sqlalchemy/pool.py", line 368, in __connect
  File "build/bdist.linux-armv6l/egg/sqlalchemy/engine/strategies.py", line 80, in connect
  File "build/bdist.linux-armv6l/egg/sqlalchemy/engine/default.py", line 279, in connect
sqlalchemy.exc.OperationalError: (OperationalError) unable to open database file None None

Thank you,

**Comment by Illizian** [comment]
:+1: I have this issue too!

**Comment by zenonasz** [comment]
Hi guys, 

i have been stragling to get this to work.

Any news with this issue?

Thanks.

**Comment by zenonasz** [comment]
Guys, I have found the way to run this!

If Still interested, let me know, i ll post the solution when i have time.

Regards,
Zenon.

**Comment by gkinsman** [comment]
Could you please post your solution rather than a post with no information and no way of contacting you?

Thanks

**Comment by vitorcac** [comment]
Hello guys,

I am facing the same issue, any news?
