### ISSUE TITLE
Error running partify on OSX

### ISSUE THREAD

**Issue by hjtenklooster** [fhats/partify#133]
After following te installation from source instructions and running run_party I had the following issues:

Can someone help me solving this?

---

DEBUG in **init** [/Users/rikkert/sources/partify/partify/**init**.py:89]:
## <Config {'JSON_AS_ASCII': True, 'USE_X_SENDFILE': False, 'SQLALCHEMY_DATABASE_URI': 'sqlite:///partify.db', 'SQLALCHEMY_POOL_SIZE': None, 'SQLALCHEMY_POOL_TIMEOUT': None, 'SESSION_COOKIE_PATH': None, 'SQLALCHEMY_RECORD_QUERIES': None, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_NAME': 'session', 'SQLALCHEMY_BINDS': None, 'SQLALCHEMY_POOL_RECYCLE': None, u'PROFILE': False, 'LOGGER_NAME': 'partify', 'DEBUG': True, 'SECRET_KEY': u'9e438019c1680bdae17da9c5cf1885b43158b88dec3f6cded737ea35edd9bf126d4a5718dbffe926a5bd96712eca562476ab8ab69d09111c197c54ff8922ac7c', 'SQLALCHEMY_NATIVE_UNICODE': None, 'MAX_CONTENT_LENGTH': None, u'SESSION_SALT': u'2785b6dfac7e3fb64033b9fa0e33c14bad7ab0306207c9a4cb239709e1d13d6c29dd8c3badd1ef9e1f054d8f6b6573e4da617534317fcd94deb647cdb13bca0b', 'SQLALCHEMY_ECHO': False, 'APPLICATION_ROOT': None, 'SERVER_NAME': None, u'SERVER_HOST': u'0.0.0.0', 'PREFERRED_URL_SCHEME': 'http', 'JSONIFY_PRETTYPRINT_REGULAR': True, 'TESTING': False, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(31), 'PROPAGATE_EXCEPTIONS': None, u'SERVER': u'tornado', 'TRAP_BAD_REQUEST_ERRORS': False, u'MPD_SERVER_HOSTNAME': u'localhost', 'JSON_SORT_KEYS': True, u'MPD_SERVER_PORT': 6600, u'LASTFM_API_KEY': u'', 'SESSION_COOKIE_HTTPONLY': True, u'SERVER_PORT': 5000, 'SEND_FILE_MAX_AGE_DEFAULT': 43200, u'SELECTION_SCHEME': u'ROUND_ROBIN', u'LASTFM_API_SECRET': u'', 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SESSION_COOKIE_SECURE': False, 'TRAP_HTTP_EXCEPTIONS': False}>

Traceback (most recent call last):
  File "./run_partify", line 23, in <module>
    start()
  File "/Users/rikkert/sources/partify/partify/**init**.py", line 105, in start
    tornado.options.enable_pretty_logging()
AttributeError: 'module' object has no attribute 'enable_pretty_logging'
Process Process-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/Users/rikkert/sources/partify/partify/decorators.py", line 66, in wrapped
    return_value = f(mpd_client, _args, *_kwargs)
  File "/Users/rikkert/sources/partify/partify/queue.py", line 455, in on_playlist_update
    ipc.update_time('playlist', time.time())
  File "/Users/rikkert/sources/partify/partify/ipc.py", line 98, in update_time
    last_updated_times[key] = time
  File "<string>", line 2, in __setitem__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 289, in SocketClient
    s.connect(address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory

**Comment by hjtenklooster** [comment]
I found out that the issue comes from tornado version 3 or higher. 

By installing tornado 2.~ it worked for me, I used the following commands:

sudo pip uninstall tornado

sudo pip install "tornado<3"
